### ISSUE TITLE
[Bug Report] Vouchers

### ISSUE THREAD

**Issue by niikoolaa04** [Crazy-Crew/Crazy-Auctions#103]
So, i'm using Vouchers plugin and when player tries to sell voucher ex. nick command voucher. It sell's it to /ah and it shows ther but item stays in players inventory, too. I get this error in console
```
null
org.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin CrazyAuctions v1.2.12-RELEASE
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException: null key in entry: null=0
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[server.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[server.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:915) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:864) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103) ~[server.jar:git-PaperSpigot-"4c7641d"]
at me.badbones69.crazyauctions.api.FileManager.saveFile(FileManager.java:204) ~[?:?]
at me.badbones69.crazyauctions.api.FileManager$Files.saveFile(FileManager.java:338) ~[?:?]
at me.badbones69.crazyauctions.Main.onCommand(Main.java:343) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-PaperSpigot-"4c7641d"]
... 15 more```

Server Version: PaperSpigot 1.8.8
Plugin Version: 1.2.12-RELEASE

**Comment by badbones69** [comment]
pastebin the voucher that is doing this.
